import re

traits_to_skip_gwas_tools = ['liu-decode-lyons-dennis-iga', 'liu-decode-lyons-iga', 'bronson-finngen-igad', 'lyons-dennis-igg', 'lim-igad']
pattern = '|'.join(re.escape(trait) for trait in traits_to_skip_gwas_tools)

wildcard_constraints:
    snp_set = 'with_mhc|sans_mhc',
    chr = "chr[0-9XY]{1,2}",
    chr_no = "[0-9XY]{1,2}",
    assembly = "hg19|hg38",
    ancestry = "eur|afr|amr|eas|sas|all",
    variant_set = "all|sans_mhc|with_mhc",
    variant_type = "all|snps_only|sans_at_gc_snps_only",
    window_size = "\\d+kb",
    flank_size = "\\d+kb",
    r2 = "0_\\d+",
    download_name = '[a-z0-9\\-]+',
    input_name = fr'^(?!.*(?:{pattern})).*$',
    draws = "\\d+",
    info = "0_\\d+",
    maf = "\\d+",
    vmiss = "\\d+",
    post_vmiss = "\\d+",
    group = "all|cases|controls",
    population = "all|eur",
    phenotype = "cvid|igad|pad|all-pid",
    read_length = "100|125|150|all",
    controls_per_case = "\\d+|max|per-length",
    seed = "\\d+",
    hwe = "\\d+",
    case_hwe = "\\d+",
    control_hwe = "\\d+",
    threshold = "gws|suggestive|\\d+",
    snp_id = "\\d+_\\d+_\\w+_\\w+",
    disease = "pid|ndd|metab",
    ukb_ethnicity = "all|white_british|white",
    ukb_relatedness = "all|unrelated",
    ukb_case_relatedness = "all|unrelated",
    ukb_control_relatedness = "all|unrelated",
    ukb_case_ethnicity = "all|white_british|white",
    ukb_control_ethnicity = "all|white_british|white",
    ukb_inclusion = "with_ukb|without_ukb|old_igad|without_bronson",
    li_join = "li_outer|li_left",
    decode_inclusion = "with_decode|without_decode",
    screen = "prescreen|postscreen",
    cfdr_inclusion = "with_cfdr|sans_cfdr",
    aux_inclusion = "with_aux|sans_aux",
    locus = "[\\w-]+"
